import Script from 'next/script';

export default function Head() {
  return (
    <>
      <title>D_D Academy</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script src="http://localhost:3000" strategy="lazyOnload" />
    </>
  );
}
